services:
  planner-container:
    build:
      context: ./planner
      dockerfile: Dockerfile
    image: planner-service-node
    networks:
      - network_name
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  worker-container:
    build:
      context: ./worker
      dockerfile: Dockerfile
      args:
        SPECIALIZATION: "all"
    image: worker-service-node
    networks:
      - network_name
    depends_on:
      - planner-container
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      replicas: 10
      update_config:
        parallelism: 1
        delay: 10s
    environment:
      - SPECIALIZATION_ENV=all

  worker-container-mult:
    build:
      context: ./worker
      dockerfile: Dockerfile
      args:
        SPECIALIZATION: "mult"
    image: worker-service-node
    networks:
      - network_name
    depends_on:
      - planner-container
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      replicas: 10
      update_config:
        parallelism: 1
        delay: 10s
    environment:
      - SPECIALIZATION_ENV=mult

  worker-container-add:
    build:
      context: ./worker
      dockerfile: Dockerfile
      args:
        SPECIALIZATION: "add"
    image: worker-service-node
    networks:
      - network_name
    depends_on:
      - planner-container
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      replicas: 10
      update_config:
        parallelism: 1
        delay: 10s
    environment:
      - SPECIALIZATION_ENV=add
networks:
  network_name:
    driver: bridge
